spring:
  bot:
    plugin-list: # 配置插件列表（有序），如果插件返回0，继续执行剩余插件，如果插件返回1，终止剩余插件执行
      - net.zzy.pbbot.plugin.LogPlugin # 日志插件,放在首位，返回0
      - net.zzy.pbbot.plugin.DailyNews # 每日新闻

server:
  port: 9762
